config/routes.rb
Rails.application.routes.draw do
  resources :product_expirations

  get 'proxy/product_targets'
  get 'proxy' => 'proxy#product_targets'
  get 'product_targets/process_refunds' => 'product_targets#process_refunds'

  resources :product_targets

  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  root :to => 'home#index'

end

app/models/product_expiration.rb
class ProductExpiration < ActiveRecord::Base
end

app/controllers/product_expirations_controller.rb
class ProductExpirationsController < ApplicationController
  before_action :set_product_expiration, only: [:show, :edit, :update, :destroy]

  # GET /product_expirations
  # GET /product_expirations.json
  def index
    @product_expirations = ProductExpiration.all
  end

  # GET /product_expirations/1
  # GET /product_expirations/1.json
  def show
  end

  # GET /product_expirations/new
  def new
    @product_expiration = ProductExpiration.new
  end

  # GET /product_expirations/1/edit
  def edit
  end

  # POST /product_expirations
  # POST /product_expirations.json
  def create
    @product_expiration = ProductExpiration.new(product_expiration_params)

    respond_to do |format|
      if @product_expiration.save
        format.html { redirect_to @product_expiration, notice: 'Product expiration was successfully created.' }
        format.json { render :show, status: :created, location: @product_expiration }
      else
        format.html { render :new }
        format.json { render json: @product_expiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_expirations/1
  # PATCH/PUT /product_expirations/1.json
  def update
    respond_to do |format|
      if @product_expiration.update(product_expiration_params)
        format.html { redirect_to @product_expiration, notice: 'Product expiration was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_expiration }
      else
        format.html { render :edit }
        format.json { render json: @product_expiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_expirations/1
  # DELETE /product_expirations/1.json
  def destroy
    @product_expiration.destroy
    respond_to do |format|
      format.html { redirect_to product_expirations_url, notice: 'Product expiration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_expiration
      @product_expiration = ProductExpiration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_expiration_params
      params.require(:product_expiration).permit(:shop, :product, :expiration, :complete)
    end
end

app/helpers/product_expirations_helper.rb
module ProductExpirationsHelper
end

app/views/product_expirations/_form.html.erb
<%= form_for(@product_expiration) do |f| %>
  <% if @product_expiration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_expiration.errors.count, "error") %> prohibited this product_expiration from being saved:</h2>

      <ul>
      <% @product_expiration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop %><br>
    <%= f.number_field :shop %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.number_field :product %>
  </div>
  <div class="field">
    <%= f.label :expiration %><br>
    <%= f.datetime_select :expiration %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_expirations/edit.html.erb
<h1>Editing Product Expiration</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_expiration %> |
<%= link_to 'Back', product_expirations_path %>

app/views/product_expirations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Expirations</h1>

<table>
  <thead>
    <tr>
      <th>Shop</th>
      <th>Product</th>
      <th>Expiration</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_expirations.each do |product_expiration| %>
      <tr>
        <td><%= product_expiration.shop %></td>
        <td><%= product_expiration.product %></td>
        <td><%= product_expiration.expiration %></td>
        <td><%= product_expiration.complete %></td>
        <td><%= link_to 'Show', product_expiration %></td>
        <td><%= link_to 'Edit', edit_product_expiration_path(product_expiration) %></td>
        <td><%= link_to 'Destroy', product_expiration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product expiration', new_product_expiration_path %>

app/views/product_expirations/new.html.erb
<h1>New Product Expiration</h1>

<%= render 'form' %>

<%= link_to 'Back', product_expirations_path %>

app/views/product_expirations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop:</strong>
  <%= @product_expiration.shop %>
</p>

<p>
  <strong>Product:</strong>
  <%= @product_expiration.product %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @product_expiration.expiration %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @product_expiration.complete %>
</p>

<%= link_to raw('Back'), "/product_targets?product_id=" + @product_expiration.product.to_s %>