config/routes.rb
Rails.application.routes.draw do
  resources :product_expirations

  get 'proxy/product_targets'
  get 'proxy' => 'proxy#product_targets'
  get 'product_targets/process_refunds' => 'product_targets#process_refunds'

  resources :product_targets

  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end
  root :to => 'home#index'

end

app/models/product_target.rb
class ProductTarget < ActiveRecord::Base

    def self.adjustPrices

      shops = Shop.all

      shops.each do |shop|
        self.adjustPrice(shop.id)
      end #shop.each

    end #method - adjustPrices

    def self.adjustPrice(shop)
      shop_session = Shop.retrieve(shop)

      # Retrieve all product targets for a shop
      product_targets = ProductTarget.where(shop: shop).all

      product_targets.each do |pt|

        product = ShopifyAPI::Product.find(pt.product)
        purchased_count = self.purchaseCount(product.id)

        if (!pt.refunded && pt.minqty <= purchased_count)
          
          #update prices
          product.variants.each do |v|
            comp_price = v.price
            v.price = pt.price
            v.compare_price = comp_price
          end
          product.save

        end #if not refunded and purchase count met
      end #product_targets.each

    end #adjustPrice

    def self.purchaseCount(product_id)
      total_orders = ShopifyAPI::Order.find(:all, :params => {:order => "created_at DESC" })
      purchased_count = 0

      total_orders.each do |o|

        o.line_items.each do |li|
          if (li.product_id == product_id)
            purchased_count += li.quantity
          end
        end #orders.each
      end #total_orders.each

      purchased_count # return
    end #method - purchaseCount
end

app/controllers/product_targets_controller.rb
class ProductTargetsController < ApplicationController

  before_filter :set_product_id
  before_action :set_product_target, only: [:show, :edit, :update, :destroy]
  around_filter :shopify_session
  before_action :load_shopify_vars

  def default_url_options
    {:product_id => @product_id}
  end

  # GET /product_targets
  # GET /product_targets.json
  def index
    set_orders()
    set_product_expiration()
    set_product_targets()
    @next_order = @product_targets.length + 1
  end

  # GET /product_targets/1
  # GET /product_targets/1.json
  def show
  end

  # GET /product_targets/new
  def new
    @next_order = 1
    
    if (params['next_order'])
      @next_order = params['next_order']
    end

    @product_target = ProductTarget.new
  end

  # GET /product_targets/1/edit
  def edit
    @next_order = @product_target.order
  end

  # POST /product_targets
  # POST /product_targets.json
  def create
    @product_target = ProductTarget.new(product_target_params)
    @product_target.shop = @shop.id

    respond_to do |format|
      if @product_target.save
        format.html { redirect_to @product_target, notice: 'Product target was successfully created.' }
        format.json { render :show, status: :created, location: @product_target }
      else
        format.html { render :new }
        format.json { render json: @product_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_targets/1
  # PATCH/PUT /product_targets/1.json
  def update
    respond_to do |format|
      if @product_target.update(product_target_params)
        format.html { redirect_to @product_target, notice: 'Product target was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_target }
      else
        format.html { render :edit }
        format.json { render json: @product_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_targets/1
  # DELETE /product_targets/1.json
  def destroy
    @product_target.destroy
    respond_to do |format|
      format.html { redirect_to product_targets_url, notice: 'Product target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #manually process refunds
  def process_refunds
    set_orders()
    ProductTarget.adjustPrice(@shop.id)
    product = ShopifyAPI::Product.find(@product_id)
    current_price = product.variants[0].price

    @orders.each do |order|

      order.line_items.each do |li|
        
        if (li.fulfillment_status != 'fulfilled')

          # capture payment
          ShopifyAPI::Transaction.create({"kind"=>"capture", "order_id" => order.id })

          if (li.product_id == @product.id && li.fulfillment_status != "fulfilled")
            
            # apply refund
            qty = li.quantity.to_i
            refund_amount = li.price.to_f - current_price.to_f

            puts refund_amount

            if (refund_amount > 0)
              total_refund = refund_amount * qty

              puts total_refund

              ShopifyAPI::Transaction.create({"amount"=>total_refund, "kind"=>"refund", "order_id" => order.id })

            end

            # fulfill li
            f = ShopifyAPI::Fulfillment.new(:order_id => order.id, :line_items =>[ { "id" => li.id } ] )
            f.save
          end

        end
        
      end

    end

    respond_to do |format|
      format.html { redirect_to product_targets_url, notice: 'Refunds successfully created' }
      format.json { head :no_content }
    end
  end

  private

    def set_orders

      total_orders = ShopifyAPI::Order.find(:all, :params => {:order => "created_at DESC" })
      @orders ||= []
      @purchased_count = 0

      total_orders.each do |o|
        product_in_order = false

        o.line_items.each do |li|
          if (li.product_id == @product.id)
            product_in_order = true
            @purchased_count += li.quantity

          end

        end

        if (product_in_order)
          @orders.push(o)
        end

      end

      ProductTarget.adjustPrice(@shop.id)
    end

    def set_product_targets

      product_targets = ProductTarget.where(product: @product.id, shop: @shop.id).all

      if product_targets.empty?

        #insert default product target based on product details from shopify
        product_target = ProductTarget.new do |pt|
          pt.shop = @shop.id
          pt.product = @product.id
          pt.minqty = 0
          pt.price = @product.variants[0].price
          pt.priceLessPrevious = 0.00
          pt.order = 1
          pt.refunded = true
        end

        product_target.save()

        product_targets = ProductTarget.where(product: @product_id, shop: @shop.id).all

      end

      @product_targets = product_targets;

    end

    def set_product_expiration

      product_expirations = ProductExpiration.where(product: @product.id, shop: @shop.id).all

      if product_expirations.empty?

        #insert default product target based on product details from shopify
        product_exp = ProductExpiration.new do |pe|
          pe.shop = @shop.id
          pe.product = @product.id
          pe.complete = false
        end

        product_exp.save()

        product_expirations = ProductExpiration.where(product: @product.id, shop: @shop.id).all

      end

      @product_expiration = product_expirations.first;

    end  

    def load_shopify_vars
      if @product_id
        @shop = ShopifyAPI::Shop.current
        @product = ShopifyAPI::Product.find(@product_id)

        if (@product)
          #product exists on shopify
        else
          redirect_to '/'
        end

      else 
        redirect_to '/'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product_target
      @product_target = ProductTarget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_target_params
      params.require(:product_target).permit(:product, :minqty, :price, :priceLessPrevious, :order)
    end

    def set_product_id
      @product_id = params['product_id']
    end

end

app/helpers/product_targets_helper.rb
module ProductTargetsHelper
end

app/views/product_targets/_form.html.erb
<%= form_for(@product_target) do |f| %>
  <% if @product_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_target.errors.count, "error") %> prohibited this product_target from being saved:</h2>

      <ul>
      <% @product_target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order , {:value => @next_order} %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.number_field :product, {:value => @product.id, :readonly => true} %>
  </div>
  <div class="field">
    <%= f.label 'Quantity Target' %><br>
    <%= f.number_field :minqty %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <input type="hidden" name="id" id="id" value="<%= @product.id %>" />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_targets/edit.html.erb
<h1>Editing Product Target</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_target %> |
<%= link_to 'Back', product_targets_path %>

app/views/product_targets/index.html.erb
<div class="product-targets-container container-fluid">

  <h1>Sales Targets</h1>

  <div class="row">
    <div class="product-display span4">

      <!-- product title -->
      <div class="product-title product-element">
        <%= @product.title %>
      </div>

      <!-- product current price -->
      <div class="product-current-price product-element">
        <span class="descr">Current Price:</span>
        <span class="value">$<%= @product.variants[0].price %></span>
      </div>

      <!-- Total Purchased -->
      <div class="product-total-purchased product-element">
        <span class="descr">Sold:</span>
        <span class="value"><%= @purchased_count %></span>
      </div>

      <!-- Total Orders -->
      <div class="product-total-orders product-element">
        <span class="descr">Orders:</span>
        <span class="value"><%= @orders.length %></span>
      </div>

      <div class="product-expiration-title">Product Expiration (UTC time)</div>

      <div>
        <%= form_for(@product_expiration) do |f| %>
          <% if @product_expiration.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product_expiration.errors.count, "error") %> prohibited this product_expiration from being saved:</h2>

              <ul>
              <% @product_expiration.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.datetime_field :expiration %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="span6 offset1">
      <table class="product-targets-table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Quantity Target</th>
            <th>Price</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @product_targets.each do |product_target| %>
            <tr>
              <td><%= product_target.order %></td>
              <td><%= product_target.minqty %></td>
              <td>$<%= product_target.price %></td>
              <td>
                <span><%= link_to 'Edit', edit_product_target_path(product_target) %></span>
                <span><%= link_to 'Remove', product_target, method: :delete, data: { confirm: 'Are you sure?' } %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Product target', new_product_target_path(:next_order => @next_order) %>
      <br />
      <br />

      <%= link_to 'Manually process refunds', :action => 'process_refunds' %>

    </div>
  </div>

</div>

app/views/product_targets/new.html.erb
<h1>New Product Target</h1>

<%= render 'form' %>

<%= link_to 'Back', product_targets_path %>

app/views/product_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_target.product %>
</p>

<p>
  <strong>Minqty:</strong>
  <%= @product_target.minqty %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product_target.price %>
</p>

<p>
  <strong>Pricelessprevious:</strong>
  <%= @product_target.priceLessPrevious %>
</p>

<p>
  <strong>Order:</strong>
  <%= @product_target.order %>
</p>

<%= link_to 'Edit', edit_product_target_path(@product_target) %> |
<%= link_to 'Back', product_targets_path %>